fivemwall = {}
fivemwall['BanPlayers'] = true
fivemwall['ScreenshotPlayers'] = true

fivemwall['UseESX'] = true
fivemwall['ESXTrigger'] = "esx:getSharedObject"
fivemwall['MechanicJobName'] = 'mechanic'
fivemwall['MaxTransferAmount'] = '50000'

fivemwall['GeneralBanWebhook'] = "https://discord.com/api/webhooks/896396806706049094/Wgr0xFI2Zs_sbRLA5O3TYP2H0Tsd5yx9ffqGZOFkxfS7Kzw1BO-R2clIdz8BZyXTZVW8"
fivemwall['EntitiesWebhookLog'] = "https://discord.com/api/webhooks/896396806706049094/Wgr0xFI2Zs_sbRLA5O3TYP2H0Tsd5yx9ffqGZOFkxfS7Kzw1BO-R2clIdz8BZyXTZVW8"
fivemwall['ExplosionWebhookLog'] = "https://discord.com/api/webhooks/896396806706049094/Wgr0xFI2Zs_sbRLA5O3TYP2H0Tsd5yx9ffqGZOFkxfS7Kzw1BO-R2clIdz8BZyXTZVW8"
fivemwall['ScreenShotWebhookLog'] = "https://discord.com/api/webhooks/896396806706049094/Wgr0xFI2Zs_sbRLA5O3TYP2H0Tsd5yx9ffqGZOFkxfS7Kzw1BO-R2clIdz8BZyXTZVW8"

fivemwall['ExplosionProtection'] = true
fivemwall['AntiGiveorRemoveWeapons'] = true
fivemwall['AntiBlacklistedWords'] = true
fivemwall['AntiBlacklistedTriggers'] = true
fivemwall['AntiClearPedTasks'] = true
fivemwall['AntiFakeChatMessages'] = true
fivemwall['AntiVPN'] = false
fivemwall['ReloadBanListTime'] = 600000
fivemwall['ReloadEntityTime'] = 10000

fivemwall['MaxPedsPerUser'] = 1
fivemwall['MaxPropsPerUser'] = 10
fivemwall['MaxVehiclesPerUser'] = 5
fivemwall['MaxEntitiesPerUser'] = 10
fivemwall['MaxParticlesPerUser'] = 3

fivemwall['AntiTazePlayers'] = true
fivemwall['WhitelistedJobs'] = {
	["police"] = true,
	["mechanic"] = true,
}

fivemwall['WhitelistedIPS'] = {
	["IP"] = true,
}
fivemwall['BlacklistedWeapons'] = { "WEAPON_RAILGUN", "WEAPON_GARBAGEBAG", "WEAPON_SNSPISTOL_MK2", "WEAPON_FLAREGUN", "WEAPON_MARKSMANPISTOL", "WEAPON_REVOLVER_MK2", "WEAPON_DOUBLEACTION", "WEAPON_SMG_MK2", "WEAPON_MACHINEPISTOL", "WEAPON_MINISMG", "WEAPON_RAYCARBINE", "WEAPON_SAWNOFFSHOTGUN", "WEAPON_ASSAULTSHOTGUN", "WEAPON_BULLPUPSHOTGUN", "WEAPON_HEAVYSHOTGUN", "WEAPON_DBSHOTGUN", "WEAPON_AUTOSHOTGUN", "WEAPON_ASSAULTRIFLE_MK2", "WEAPON_CARBINERIFLE_MK2", "WEAPON_ADVANCEDRIFLE", "WEAPON_SPECIALCARBINE_MK2", "WEAPON_BULLPUPRIFLE", "WEAPON_BULLPUPRIFLE_MK2", "WEAPON_COMPACTRIFLE", "WEAPON_MG", "WEAPON_COMBATMG", "WEAPON_COMBATMG_MK2", "WEAPON_SNIPERRIFLE", "WEAPON_HEAVYSNIPER", "WEAPON_HEAVYSNIPER_MK2", "WEAPON_MARKSMANRIFLE", "WEAPON_MARKSMANRIFLE_MK2", "WEAPON_RPG", "WEAPON_GRENADELAUNCHER", "WEAPON_GRENADELAUNCHER_SMOKE", "WEAPON_MINIGUN", "WEAPON_FIREWORK", "WEAPON_RAILGUN", "WEAPON_HOMINGLAUNCHER", "WEAPON_COMPACTLAUNCHER", "WEAPON_RAYMINIGUN", "WEAPON_GRENADE", "WEAPON_BZGAS", "WEAPON_MOLOTOV", "WEAPON_STICKYBOMB", "WEAPON_PROXMINE", "WEAPON_SNOWBALL", "WEAPON_PIPEBOMB", "WEAPON_BALL", "WEAPON_SMOKEGRENADE", "WEAPON_ROCKET", "WEAPON_EXPLOSION ", "WEAPON_FLARE", "WEAPON_MUSKET" }
fivemwall['BlacklistedWords'] = {	"Ham Mafia",	"HamHaxia",	'Brutan',	'Desudo',	'EulenCheats',	"85.190.90.118",	"AlphaV ~ 5391",	"Baran#8992",	"Fallen#0811",	"hammafia.com",	"iLostName#7138",	"Soviet Bear",	"vjuton.pl",	"www.renalua.com",	"34ByTe Community", 	"Anti-Lynx",	"Ham Mafia", 	"HamHaxia", 	"Lynx 8",	"lynxmenu.com", 	"lynxmenu",	"Melon#1379",	"Rena 8",	"www.lynxmenu.com",	"Xanax#0134", 	">:D Player Crash",	"333",	"333GANG",	"34ByTe Community",	"Anti-LRAC",	"aries.pl",	"aries",	"Aries98",	"dc.xaries.pl",	"dezet",	"discord.gg", 	"discord.gg/",	"Eulen",	"EulenCheat",	"KoGuSzEk#3251",	"Lynx",	"lynxmenu.com - Cheats & Anti-Cheats!",	"lynxmenu.com",	"MARVIN menu",	"Rena",	"Xanax#0134",	"xaries",	"XARIES",	"yo many",	"youtube.com/c/Aries98/", }

fivemwall['BlacklistedTriggers'] = {
	"redst0nia:checking",
	"esx_mafiajob:confiscatePlayerItem",
	"lscustoms:payGarage",
	"vrp_slotmachine:server:2",
	"esx_fueldelivery:pay",
	"AdminMenu:giveBank",
	"AdminMenu:giveCash",
	"NB:recruterplayer",
	"js:jailuser",
	"OG_cuffs:cuffCheckNearest",
	"cuffServer",
	"cuffGranted",
	"esx_mechanicjob:startCraft",
	"esx_vehicletrunk:giveDirty",
	"gambling:spend",
	"AdminMenu:giveDirtyMoney",
	"mission:completed",
	"truckerJob:success",
	"99kr-burglary:addMoney",
	"esx_jailer:unjailTime",
	"DiscordBot:playerDied",
	"hentailover:xdlol",
	"antilynx8:anticheat",
	"antilynxr6:detection",
	"antilynx8r4a:anticheat",
	"antilynxr4:detect",
	"js:jailuser", 
	"ynx8:anticheat",
	"lynx8:anticheat",
	"adminmenu:allowall",
	"h:xd",
	"ljail:jailplayer",
	"adminmenu:setsalary",
	"adminmenu:cashoutall",
	"HCheat:TempDisableDetection",
	"esx_drugs:pickedUpCannabis",
	"esx_drugs:processCannabis",
	"esx-qalle-hunting:reward",
	"esx-qalle-hunting:sell",
	"esx_mecanojob:onNPCJobCompleted",
	"BsCuff:Cuff696999",
	"veh_SR:CheckMoneyForVeh",
	"mellotrainer:adminTempBan",
	"mellotrainer:adminKick",
	"d0pamine_xyz:getFuckedNigger",
	"esx_communityservice:sendToCommunityService",
	"crown_xyz:getFuckedNigger",
	"kashactersS:DeleteCharacter",
	"NB:destituerplayer",
}
fivemwall['BlockedExplosions'] = {
	0,
	1,
	2,
	3,
	4,
	5,
	25,
	32,
	33,
	35,
	36,
	37,
	38
}
fivemwall['BlacklistedModels'] = {
	"skylift",
	"valkyrie2",
	"airbus",
	"hunter",
	"bus",
	"tug",
	"bulldozer",
	"mule2",
	"trash",
	"armytanker",
	"armytrailer",
	"armytrailer2",
	"baletrailer",
	"boattrailer",
	"cablecar",
	"docktrailer",
	"freighttrailer",
	"graintrailer",
	"proptrailer",
	"raketrailer",
	"tr2",
	"tr3",
	"tr4",
	"trflat",
	"tvtrailer",
	"tanker",
	"tanker2",
	"tankercar",
	"trailerlarge",
	"trailerlogs",
	"trailersmall",
	"trailers3",
	"trailers4",
	'RHINO',
	'AKULA',
	'SAVAGE',
	'HUNTER',
	'BUZZARD',
	'ANNIHILATOR',
	'VALKYRIE',
	'HYDRA',
	'APC',
	'Trailersmall2',
	'Lazer',
	'oppressor',
	'mogul',
	'barrage',
	'Khanjali',
	'volatol',
	'chernobog',
	'avenger',
	'stromberg',
	'nightshark',
	'besra',
	'babushka ',
	'starling',
	'insurgent',
	'cargobob',
	'cargobob2',
	'cargobob3',
	'cargobob4',
	'caracara',
	'deluxo',
	'menacer',
	'scramjet',
	'oppressor2',
	'revolter',
	'viseris',
	'savestra',
	'thruster',
	'ardent',
	'dune3',
	'tampa3',
	'halftrack',
	'nokota',
	'strikeforce',
	'bombushka',
	'molotok',
	'granger',
	'pyro',
	'ruiner2',
	'limo2',
	'technical',
	'technical2',
	'technical3',
	'jb700w',
	'blazer5',
	'insurgent3',
	'boxville5',
	'bruiser',
	'bruiser2',
	'bruiser3',
	'brutus',
	'brutus2',
	'brutus3',
	'cerberus',
	'cerberus2',
	'cerberus3',
	'dominator4',
	'dominator5',
	'dominator6',
	'impaler2',
	'impaler3',
	'impaler4',
	'imperator',
	'imperator2',
	'imperator3',
	'issi4',
	'issi5',
	'issi6',
	'monster3',
	'monster4',
	'monster5',
	'scarab',
	'scarab2',
	'scarab3',
	'slamvan4',
	'slamvan5',
	'slamvan6',
	'zr380',
	'zr3802',
	'zr3803',
	'alphaz1',
	'avenger2',
	'blimp',
	'blimp2',
	'blimp3',
	'cargoplane',
	'cuban800',
	'dodo',
	'duster',
	'howard',
	'jet',
	'luxor',
	'luxor2',
	'mammatus',
	'microlight',
	'miljet',
	'nimbus',
	'rogue',
	'seabreeze',
	'shamal',
	'stunt',
	'titan',
	'tula',
	'velum',
	'velum2',
	'vestra',

	-- PEDS
	"s_m_y_swat_01",
	"a_m_o_acult_01",
	"ig_wade",
	"s_m_y_hwaycop_01",
	"A_M_Y_ACult_01",
	's_m_m_movalien_01',
	's_m_m_movallien_01',
	'u_m_y_babyd',
	'CS_Orleans',
	'A_M_Y_ACult_01',
	'S_M_M_MovSpace_01',
	'U_M_Y_Zombie_01',
	's_m_y_blackops_01',
	'a_f_y_topless_01',
	'a_c_boar',
	'a_c_cat_01',
	'a_c_chickenhawk',
	'a_c_chimp',
	'a_c_chop',
	'a_c_cormorant',
	'a_c_cow',
	'a_c_coyote',
	'a_c_crow',
	'a_c_dolphin',
	'a_c_fish',
	'a_c_hen',
	'a_c_humpback',
	'a_c_husky',
	'a_c_killerwhale',
	'a_c_mtlion',
	'a_c_pigeon',
	'a_c_poodle',
	'a_c_pug',
	'a_c_rabbit_01',
	'a_c_rat',
	'a_c_retriever',
	'a_c_rhesus',
	'a_c_rottweiler',
	'a_c_sharkhammer',
	'a_c_sharktiger',
	'a_c_shepherd',
	'a_c_stingray',
	'a_c_westy',
	'CS_Orleans',
}
fivemwall['WhitelistedProps'] = {
	"prop_ballistic_shield",
	"prop_amb_phone",
	"xm_prop_x17_tem_control_01",
	"player_zero",
	"prop_bowling_ball",
	"p_parachute1_mp_s"
}
